version: '3.7'

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    networks:
      - iot
    ports:
      - "1883:1883"
    volumes:
      - mosquitto:/mosquitto
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped

  nodered:
    container_name: nodered
    image: nodered/node-red
    networks:
      - iot
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data 
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped
  
  influxdb:
    container_name: influxdb
    image: "influxdb"
    networks:
      - iot
    ports:
      - "8086:8086"
    volumes:
      - influxdb-var:/var/lib/influxdb 
      - influxdb-etc:/etc/influxdb 
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: "grafana/grafana"
    networks:
      - iot
    ports:
      - "3000:3000"
    volumes:
      - grafana-etc:/etc/grafana
      - grafana-lib:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,natel-discrete-panel,briangann-gauge-panel,vonage-status-panel,neocat-cal-heatmap-panel,ryantxu-ajax-panel,petrslavotinek-carpetplot-panel,grafana-piechart-panel
    env_file: .env
    restart: unless-stopped
  
networks:
  iot:
    name: allwize-iot

volumes:
  mosquitto:
  nodered:
  influxdb-var:
  influxdb-etc:
  grafana-etc:
  grafana-lib: