version: '3.7'

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.13
    networks:
      - iot
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/mosquitto/data:/mosquitto/data 
      - ./data/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped

  nodered:
    container_name: nodered
    image: nodered/node-red
    networks:
      - iot
    ports:
      - "1880:1880"
    volumes:
      - ./data/nodered:/data 
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped
  
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.4-alpine
    networks:
      - iot
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./data/influxdb:/var/lib/influxdb 
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: "grafana/grafana"
    networks:
      - iot
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,natel-discrete-panel,briangann-gauge-panel,vonage-status-panel,neocat-cal-heatmap-panel,ryantxu-ajax-panel,petrslavotinek-carpetplot-panel,grafana-piechart-panel
    env_file: .env
    restart: unless-stopped
  
networks:
  iot:
    name: allwize-iot
